services:
  spark:
    build:
      context: ./spark-app
      dockerfile: Dockerfile.dev
    image: bitnami/spark:latest
    container_name: spark-container
    volumes:
      - ./spark-model:/app/model
    ports:
      - '4040:4040'
    command: spark-submit --master local[*] /app/train_model.py
volumes:
  spark-model:
