services:
  spark:
    build:
      context: ./spark-app
      dockerfile: Dockerfile.dev
    image: bitnami/spark:latest
    container_name: spark-container
    ports:
      - '4040:4040' # Spark Web UI
    volumes:
      - ./spark-app:/app # Mount local directory with Spark script
    command: spark-submit --master local[*] /app/train_model.py
