services:
  spark-master:
    restart: always
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - '7077:7077'
      - '8080:8080'
    command: ['spark-class', 'org.apache.spark.deploy.master.Master']

  spark-worker:
    restart: always
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    command:
      [
        'spark-class',
        'org.apache.spark.deploy.worker.Worker',
        'spark://spark-master:7077',
      ]

  flask-app:
    build:
      context: ./flask-api
      dockerfile: Dockerfile.dev
    ports:
      - '8082:5000'
    volumes:
      - ./flask-api:/app
      - ./spark-model:/app/model
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --reload
    depends_on:
      - spark-worker
      - spark-master

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8081
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - flask-app
volumes:
  spark-model:

networks:
  default:
    name: app-network
