FROM bitnami/spark:latest

USER root

# Install dependencies
RUN apt-get update && apt-get install -y python3-pip

# Copy requirements.txt and install Python packages
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt


# Copy your training script into the container
COPY train_model.py /app/train_model.py

WORKDIR /app

CMD ["spark-submit", "--master", "local[*]", "/app/train_model.py"]