
FROM bitnami/spark:3.4.1

USER root
RUN apt-get update && apt-get install -y python3-pip python3-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


WORKDIR /app

COPY . /app

EXPOSE 5000


CMD ["flask", "run", "--host=0.0.0.0"]

